export const tempData = [
  {
    id: '1',
    date: '2023-06-18T20:28:19+00:00',
    user: {
      img: '',
      name: 'Christian COLLIN',
      function: 'Electrician',
    },
    age: '33',
    department: 'Electrical',
    role: 'Worker',
    company: 'img',
    reportTo: {
      img: '',
      name: 'Aimarah Oussama',
      function: 'Electrician',
    },
    phone: 'MA 07080866',
    email: 'email@mail.com',
    status: true,
  },
  {
    id: '2',
    date: '2023-06-18T20:28:19+00:00',
    user: {
      img: '',
      name: 'Christian COLLIN',
      function: 'Electrician',
    },
    age: '33',
    department: 'Electrical',
    role: 'Worker',
    company: 'img',
    reportTo: {
      img: '',
      name: 'Aimarah Oussama',
      function: 'Electrician',
    },
    phone: 'MA 07080866',
    email: 'prewitt.lemaitre@newelec.be',
    status: true,
  },
  {
    id: '3',
    date: '2023-06-18T20:28:19+00:00',
    user: {
      img: '',
      name: 'Christian COLLIN',
      function: 'Electrician',
    },
    age: '33',
    department: 'Electrical',
    role: 'Worker',
    company: 'img',
    reportTo: {
      img: '',
      name: 'Aimarah Oussama',
      function: 'Electrician',
    },
    phone: 'MA 07080866',
    email: 'email@mail.com',
    status: true,
  },
  {
    id: '4',
    date: '2023-06-18T20:28:19+00:00',
    user: {
      img: '',
      name: 'Christian COLLIN',
      function: 'Electrician',
    },
    age: '33',
    department: 'Electrical',
    role: 'Worker',
    company: 'img',
    reportTo: {
      img: '',
      name: 'Aimarah Oussama',
      function: 'Electrician',
    },
    phone: 'MA 07080866',
    email: 'email@mail.com',
    status: true,
  },
  {
    id: '5',
    date: '2023-06-18T20:28:19+00:00',
    user: {
      img: '',
      name: 'Christian COLLIN',
      function: 'Electrician',
    },
    age: '33',
    department: 'Electrical',
    role: 'Worker',
    company: 'img',
    reportTo: {
      img: '',
      name: 'Aimarah Oussama',
      function: 'Electrician',
    },
    phone: 'MA 07080866',
    email: 'prewitt.lemaitre@newelec.be',
    status: true,
  },
  {
    id: '6',
    date: '2023-06-18T20:28:19+00:00',
    user: {
      img: '',
      name: 'Christian COLLIN',
      function: 'Electrician',
    },
    age: '33',
    department: 'Electrical',
    role: 'Worker',
    company: 'img',
    reportTo: {
      img: '',
      name: 'Aimarah Oussama',
      function: 'Electrician',
    },
    phone: 'MA 07080866',
    email: 'email@mail.com',
    status: true,
  },
];
