export const tempData = [
  {
    id: 0,
    name: "BESIX Group",
    site_id: "",
    acronym: "",
    legal_form: "",
    tva: "",
    nace: "",
    desc: "",
    address: "Rue du Canal, 7100 La Louvière, Belgium",
    n_address: "",
    box: "",
    zip_code: "",
    city: "",
    country: "",
    phoneCode: "",
    phoneNum: "",
    email: "",
    website: "",
    status: true,
    contacts: [{ fname: "", lname: "", acm: "", bd: "", phone: "", email: "" }],
    picture_url: "/src/assets/temp/besix.png",
    person_contractors_count: 2,
  },
  {
    id: 1,
    name: "NexaCore",
    site_id: "",
    acronym: "",
    legal_form: "",
    tva: "",
    nace: "",
    desc: "",
    address: "Rue du Canal, 7100 La Louvière, Belgium",
    n_address: "",
    box: "",
    zip_code: "",
    city: "",
    country: "",
    phoneCode: "",
    phoneNum: "",
    email: "",
    website: "",
    status: true,
    contacts: [{ fname: "", lname: "", acm: "", bd: "", phone: "", email: "" }],
    picture_url: "/src/assets/temp/besix.png",
    person_contractors_count: 2,
  },
  {
    id: 2,
    name: "EliteWave",
    site_id: "",
    acronym: "",
    legal_form: "",
    tva: "",
    nace: "",
    desc: "",
    address: "Rue du Canal, 7100 La Louvière, Belgium",
    n_address: "",
    box: "",
    zip_code: "",
    city: "",
    country: "",
    phoneCode: "",
    phoneNum: "",
    email: "",
    website: "",
    status: false,
    contacts: [{ fname: "", lname: "", acm: "", bd: "", phone: "", email: "" }],
    picture_url: "/src/assets/temp/besix.png",
    person_contractors_count: 2,
  },
  {
    id: 3,
    name: "NovoGenius",
    site_id: "",
    acronym: "",
    legal_form: "",
    tva: "",
    nace: "",
    desc: "",
    address: "Rue du Canal, 7100 La Louvière, Belgium",
    n_address: "",
    box: "",
    zip_code: "",
    city: "",
    country: "",
    phoneCode: "",
    phoneNum: "",
    email: "",
    website: "",
    status: false,
    contacts: [{ fname: "", lname: "", acm: "", bd: "", phone: "", email: "" }],
    picture_url: "/src/assets/temp/besix.png",
    person_contractors_count: 2,
  },
  {
    id: 4,
    name: "QuantumShift",
    site_id: "",
    acronym: "",
    legal_form: "",
    tva: "",
    nace: "",
    desc: "",
    address: "Rue du Canal, 7100 La Louvière, Belgium",
    n_address: "",
    box: "",
    zip_code: "",
    city: "",
    country: "",
    phoneCode: "",
    phoneNum: "",
    email: "",
    website: "",
    status: true,
    contacts: [{ fname: "", lname: "", acm: "", bd: "", phone: "", email: "" }],
    picture_url: "/src/assets/temp/besix.png",
    person_contractors_count: 2,
  },
  {
    id: 5,
    name: "CogniCore",
    site_id: "",
    acronym: "",
    legal_form: "",
    tva: "",
    nace: "",
    desc: "",
    address: "Rue du Canal, 7100 La Louvière, Belgium",
    n_address: "",
    box: "",
    zip_code: "",
    city: "",
    country: "",
    phoneCode: "",
    phoneNum: "",
    email: "",
    website: "",
    status: false,
    contacts: [{ fname: "", lname: "", acm: "", bd: "", phone: "", email: "" }],
    picture_url: "/src/assets/temp/besix.png",
    person_contractors_count: 2,
  },
  {
    id: 6,
    name: "VantagePeak",
    site_id: "",
    acronym: "",
    legal_form: "",
    tva: "",
    nace: "",
    desc: "",
    address: "Rue du Canal, 7100 La Louvière, Belgium",
    n_address: "",
    box: "",
    zip_code: "",
    city: "",
    country: "",
    phoneCode: "",
    phoneNum: "",
    email: "",
    website: "",
    status: true,
    contacts: [{ fname: "", lname: "", acm: "", bd: "", phone: "", email: "" }],
    picture_url: "/src/assets/temp/besix.png",
    person_contractors_count: 2,
  },
];
